# Generated by Django 4.1 on 2024-06-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="age",
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
