# Generated by Django 4.1 on 2024-06-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0004_remove_comment_post_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="www.post"
            ),
            preserve_default=False,
        ),
    ]
